version: "3.7"

services:
  cortex:
    image: cortex
      command: ["sh", "-c", "sleep 3 && exec ./cortex -config.file=/etc/cortex/config.yaml -target=ingester -server.http-listen-port=8002 -server.grpc-listen-port=9002"]
      depends_on:
        - consul
        - minio
      ports:
        - 8002:8002
        - 9002:9002
      volumes:
        - .data-ingester-1:/tmp/cortex-tsdb-ingester:delegated


  leafbus:
    image: "slimbean/leafbus:latest"
    #restart: "always"
    network_mode: "host"
