auth_enabled: false

server:
  http_listen_port: 8002
  grpc_listen_port: 9002
  grpc_server_max_recv_msg_size: 16777216
  grpc_server_max_send_msg_size: 16777216

ingester:
  max_transfer_retries: 0

  lifecycler:
    # We want to start immediately.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

querier:
  query_ingesters_within: 1000000h # always query ingesters

tsdb:
  dir: /srv/cortex-tsdb-ingester
  ship_interval: 0 #disable shipping
  block_ranges_period: [ 15m ]
  retention_period: 336h #14days
  backend: filesystem

  bucket_store:
    sync_dir: /srv/cortex-tsdb-querier

  filesystem:
    dir: /srv/cortex-tsdb

storage:
  engine: tsdb
