auth_enabled: false

querier:
  query_ingesters_within: 15m

server:
  http_listen_port: 8003
  grpc_listen_port: 9003
  grpc_server_max_recv_msg_size: 16777216
  grpc_server_max_send_msg_size: 16777216

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 15m
  chunk_retain_period: 30s
  chunk_encoding: none
  max_transfer_retries: 0
  chunk_target_size: 1536000 # 1.5MB
  max_chunk_age: 15m

schema_config:
  configs:
    - from: 2020-04-20
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  max_chunk_batch_size: 1
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /var/lib/loki/index
    cache_location: /var/lib/loki/boltdb-cache
  filesystem:
    directory: /var/lib/loki/chunks
