version: "3.7"

services:
  cortex:
    image: slimbean/cortex-amd:latest
    command: "-config.file=/etc/cortex/config.yaml -server.http-listen-port=8002 -querier.query-ingesters-within=-10s"
    ports:
      - 8002:8002
    volumes:
      - "/home/ed/leaf/cortex:/srv/cortex"
      - "./cortex-config.yaml:/etc/cortex/config.yaml"

  loki:
    image: slimbean/loki-amd:latest
    command: "-config.file=/etc/loki/loki-config.yaml -log.level=debug"
    volumes:
      - "/home/ed/leaf/loki:/var/lib/loki"
      - "./loki-config.yaml:/etc/loki/loki-config.yaml"
    ports:
      - 8003:8003
      - 9003:9003
#  thanos-store:
#    image: quay.io/thanos/thanos:v0.10.1
#    volumes:
#      - "./bucket.yaml:/etc/thanos/bucket_config.yaml"
#    command:
#      - 'store'
#      - '--log.level=debug'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--data-dir=/tmp/thanos/store'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
#  thanos-querier:
#    image: quay.io/thanos/thanos:v0.10.1
#    command:
#      - 'query'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--query.replica-label=replica'
#      - '--store=thanos-store:10091'
#    ports:
#      - 10902:10902
  grafana:
    image: slimbean/grafana-amd:latest
    ports:
      - "3000:3000"
    network_mode: "host"
    volumes:
      - "grafana-storage:/var/lib/grafana"


volumes:
  grafana-storage:

