---
- name: Setup Leaf Pi
  hosts: leaf
  user: pi
  become: yes
  roles:
    - node_exporter
  tasks:
    - name: Create grafana config dir
      file:
        path: /home/pi/grafana/
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'
      tags:
        - grafana
    - name: Create agent wal dir
      file:
        path: /srv/agent-wal/
        state: directory
        mode: '0755'
      tags:
        - agent-config
    - name: Copy agent config
      copy:
        src: files/agent-config.yaml
        dest: /home/pi/agent-config.yaml
      tags:
        - agent-config
        - agent
#    - name: Copy systemd file
#      copy:
#        src: files/agent.service
#        dest: /etc/systemd/system/agent.service
#      tags:
#        - agent
#    - name: Setup agent service
#      systemd:
#        daemon_reload: yes
#        name: agent
#        state: restarted
#        enabled: yes
#      tags:
#        - agent
    - name: Create cortex chunks dir
      file:
        path: /srv/cortex-tsdb-ingester/
        state: directory
        mode: '0755'
      tags:
        - cortex-config
    - name: Create cortex chunks dir
      file:
        path: /srv/cortex-tsdb/
        state: directory
        mode: '0777'
      tags:
        - cortex-config
    - name: Create cortex config dir
      file:
        path: /home/pi/cortex/
        state: directory
        mode: '0755'
      tags:
        - cortex-config
    - name: Copy cortex config
      template:
        src: files/cortex-config.yaml
        dest: /home/pi/cortex/
      tags:
        - cortex-config
    - name: Create loki chunks dir
      file:
        path: /srv/loki/
        state: directory
        mode: '0777'
      tags:
        - loki-config
    - name: Create loki config dir
      file:
        path: /home/pi/loki/
        state: directory
        mode: '0755'
      tags:
        - loki-config
    - name: Copy loki config
      copy:
        src: files/loki-config.yaml
        dest: /home/pi/loki/
      tags:
        - loki-config
#  - name: Install packages
#    apt:
#      name: "{{ packages }}"
#    vars:
#      packages:
#        - hostapd
#        - dnsmasq
#  - name: Copy hostapd conf
#    copy:
#      src: files/hostapd.conf
#      dest: /etc/hostapd/hostapd.conf
#      mode: u=rw,g=r,o=
#  - name: Copy dnsmasq conf
#    copy:
#      src: files/dnsmasq.conf
#      dest: /etc/dnsmasq.conf
#      mode: u=rw,g=r,o=r
