---
- name: Setup Leaf Pi
  hosts: leaf
  user: ubuntu
  become: yes
  roles:
    - node_exporter
  tasks:
    - name: Copy agent config
      copy:
        src: files/agent-config.yml
        dest: /home/ubuntu/agent-config.yml
      tags:
        - agent-config
        - agent
    - name: Copy systemd file
      copy:
        src: files/agent.service
        dest: /etc/systemd/system/agent.service
      tags:
        - agent
    - name: Setup agent service
      systemd:
        daemon_reload: yes
        name: agent
        state: restarted
        enabled: yes
      tags:
        - agent
    - name: Create loki chunks dir
      file:
        path: /srv/loki/
        state: directory
        mode: '0755'
      tags:
        - loki-config
    - name: Create loki config dir
      file:
        path: /home/ubuntu/loki/
        state: directory
        mode: '0755'
      tags:
        - loki-config
    - name: Copy loki config
      copy:
        src: files/loki-config.yaml
        dest: /home/ubuntu/loki/
      tags:
        - loki-config
#  - name: Install packages
#    apt:
#      name: "{{ packages }}"
#    vars:
#      packages:
#        - hostapd
#        - dnsmasq
#  - name: Copy hostapd conf
#    copy:
#      src: files/hostapd.conf
#      dest: /etc/hostapd/hostapd.conf
#      mode: u=rw,g=r,o=
#  - name: Copy dnsmasq conf
#    copy:
#      src: files/dnsmasq.conf
#      dest: /etc/dnsmasq.conf
#      mode: u=rw,g=r,o=r
