version: "3.7"

services:
  cortex:
    image: slimbean/cortex:latest
    environment:
      - GODEBUG=madvdontneed=1
    command: "-config.file=/etc/cortex/cortex-config.yaml -target=writer"
    restart: always
    ports:
      - 8002:8002
      - 9002:9002
    volumes:
      - "/home/pi/cortex/cortex-config.yaml:/etc/cortex/cortex-config.yaml"
      - "/srv/cortex-tsdb-ingester:/srv/cortex-tsdb-ingester"
  loki:
    image: grafana/loki:master-a4d671b
    environment:
      - GODEBUG=madvdontneed=1
    command: "-config.file=/etc/loki/loki-config.yaml -log.level=debug"
    #restart: always
    volumes:
      - "/srv/loki:/var/lib/loki"
      - "/home/pi/loki/loki-config.yaml:/etc/loki/loki-config.yaml"
    ports:
      - 8003:8003
      - 9003:9003
  grafana:
    image: grafana/grafana:6.6.2
    user: "1000"
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    network_mode: "host"
    ports:
      - 3000:3000
    volumes:
      - "/home/pi/grafana:/var/lib/grafana"




#  leafbus:
#    image: "slimbean/leafbus:latest"
#    #restart: "always"
#    network_mode: "host"
